name: CI/CD PIPLEINE
on:
  push:
    branches:
      - main
jobs:
  ci_cd:
    runs_on: ubuntu-latest
    steps:
      - name: code
        run: echo "write code"
      - name: build
        run: echo "build code"
      - name: Test
        run: echo "test code"
      - name: Deploy
        run: deploy code
