name: Work on Docker
on:
  workflow_dispatch: null
jobs:
  daily-greet:
    runs-on: ubuntu-latest
    steps:
      - name: good-morning
        run: echo "Good Morning"
      - name: good-night
        run: echo "Good-night"
 
