#This github action will say goodbye
name: Goodbye
on:
  push:
    branches:
      - main
jobs:
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Say goodbye to all the users
        run: echo "GoODBYE $USER"
      - name: Say goodbye to all
        run: echo "Goodbye all"
