---
name: Hello workflow
on:
  push:
    branches:
      - main
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "Hello Devops!!"
      - name: ay hello to username
        run: echo "Hello $USER"
  details:
    runs-on: ubuntu-latest
    steps:
      - name: show what is the version of python,docker, etc.
        run: docker --version && python --version
